### ISSUE TITLE
[Bug] Replays currently not working

### ISSUE THREAD

**Issue by DennisvHest** [BeatLeader/BeatSaber-Web-Replays#28]
Hi, I recently noticed that (seemingly) no replays are working correctly. The notes, sabers and headset are not moving.

In the javascript console, I see these errors:
![image](https://github.com/BeatLeader/BeatSaber-Web-Replays/assets/18610083/2d93806c-7911-4684-9c95-d741759e5904)

I have tried it in Chrome, Firefox and Edge, but all have this issue.

Could this be fixed? I'd really appreciate it! I really like the web replays.

**Comment by NSGolova** [comment]
Hi, can you please send a link to some replay you are having issues with?

**Comment by NSGolova** [comment]
I got it, it's fixed now. I highly encourage you to switch to the BeatLeader leaderboard for an even better replay experience.

**Comment by DennisvHest** [comment]
@NSGolova Thanks for the quick fix!
