### ISSUE TITLE
Replay breaks/stops registering hits

### ISSUE THREAD

**Issue by f1amy** [BeatLeader/BeatSaber-Web-Replays#37]
https://replay.beatleader.xyz/?scoreId=15467535

From 1:43 the sabers don't register hit on notes and just pass trough them.

**Comment by f1amy** [comment]
https://replay.beatleader.xyz/?scoreId=15467685 0:10 the same thing happens

**Comment by bleetube** [comment]
your replay links don't work anymore

but yeah I've noticed this too, specifcally on [OST 7 maps](https://beatleader.xyz/playlist/76122).

I'll add some replays shortly

**Comment by f1amy** [comment]
Yeah, sorry, just played the other day and forgot that the scores might improve

Here's new ones:
https://replay.beatleader.xyz/?scoreId=15473147 - Untamed
https://replay.beatleader.xyz/?scoreId=15597918 - Untamed
https://replay.beatleader.xyz/?scoreId=15598118 - Lustre

**Comment by AngusIrwin** [comment]
Had the same issue with some maps from the OSTs on 1.37.0, thought you could use the data.

OST V
Firestarter on Expert: https://replay.beatleader.xyz/?scoreId=15935112
I Wanna Be A Machine on Expert: https://replay.beatleader.xyz/?scoreId=15953695
I Wanna Be A Machine on Expert+: https://replay.beatleader.xyz/?scoreId=15722898

OST 7
Lustre on Expert: https://replay.beatleader.xyz/?scoreId=15627692
Untamed on Expert: https://replay.beatleader.xyz/?scoreId=15934897

Several maps on the OSTs don't have this issue, such as World Wide Web and The Master on Expert. It doesn't occur on any custom maps either.

If you want details on mods, configs, etc let me know.

**Comment by bleetube** [comment]
I just saw this on a non-OST track [NULCTRL](https://replay.beatleader.xyz/?scoreId=16176059)

BeatSaber v1.34.2
BeatLeader 0.9.8

**Comment by cody-ferguson** [comment]
Seems like these is a problem with the replays, not the app

**Comment by f1amy** [comment]
FYI ArcViewer does not have this problem. They might be fixing this bug in code (no warnings in console), either way it is fixable.

For example: https://allpoland.github.io/ArcViewer/?scoreId=15598118

**Comment by NSGolova** [comment]
Fixed👍
