### ISSUE TITLE
ME Maps with Precise Placement only place on the X-Axis on Obstacles

### ISSUE THREAD

**Issue by UrkiMimi** [BeatLeader/BeatSaber-Web-Replays#39]
Title 
https://replay.beatleader.xyz/?scoreId=16542994

**Comment by NSGolova** [comment]
Fixed!

**Comment by UrkiMimi** [comment]
This one bugfix made noodle charts like midnight lady a little more viewable lol
![image](https://github.com/user-attachments/assets/5c42a4d0-b03c-4fb0-8685-242efaa85712)

**Comment by NSGolova** [comment]
<img width="530" alt="image" src="https://github.com/user-attachments/assets/0a34fe83-c726-47e2-9fa6-84db13b33f22">

somewhat readable even, I'll look what the biggest issues are with it to make it at least viewable
